### ISSUE TITLE
Array support

### ISSUE THREAD

**Issue by maximaub** [yukihiko-shinoda/yaml-dataclass-config#18]
Hello, does it support yaml arrays ? If so, could you please add an example to do so in the README.md please ?

**Comment by maximaub** [comment]
@yukihiko-shinoda up please

**Comment by yukihiko-shinoda** [comment]
Hi, I'm sorry for late to notice this post, and thank you for your question.

Before updating README.md, can I confirm that the following example becomes your help to understand ?

config.yml:

```yaml
place: Paris
weather: clear
museums:
  - Louvre Museum
  - Musée d'Orsay
  - Musée de l'Orangerie
  - Centre Pompidou
  - Atelier des Lumières
  - Louis Vuitton Foundation
```

test.py:

```python
from dataclasses import dataclass, field
from yamldataclassconfig.config import YamlDataClassConfig


@dataclass
class Config(YamlDataClassConfig):
    place: str = None
    weather: str = None
    museums: list[str] = field(default_factory=list)


CONFIG: Config = Config()


def main():
    CONFIG.load()
    print(CONFIG.place)
    print(CONFIG.weather)
    print(CONFIG.museums)


if __name__ == '__main__':
    main()
```

Result:

```console
$ python test.py
Paris
clear
['Louvre Museum', "Musée d'Orsay", "Musée de l'Orangerie", 'Centre Pompidou', 'Atelier des Lumières', 'Louis Vuitton Foundation']
```

If you got understand, it's much helps to let me know what point was difficult to understand.
